/// <reference types="react-native-css/types" />

// NOTE: This file is generated by react-native-css and should be committed.

declare module "*.css" {
  const content: void;
  export default content;
}
